blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/wangfenghuan/w-next-ai-drawio/discussions
    about: Have questions or ideas? Feel free to start a discussion
